Handle case when table is defined as global.
*Problem*:
```
TypeError: <class 'troposphere.dynamodb.GlobalTable'>: Locations.SSESpecification is <class 'troposphere.dynamodb.SSESpecification'>, expected <class 'troposphere.dynamodb.GlobalTableSSESpecification'>
```

*Solution*
Just pass correct `*Specification` class.